//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractorRegistry
    {
        public int RegistryID { get; set; }
        public int ContractorNo { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string IDNumber { get; set; }
        public byte IDType { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyCRNo { get; set; }
        public Nullable<double> PurchaseOrderNo { get; set; }
        public string JobTitle { get; set; }
        public string MobileNo { get; set; }
        public string VisitedCostCenter { get; set; }
        public int SupervisorEmpNo { get; set; }
        public string SupervisorEmpName { get; set; }
        public string PurposeOfVisit { get; set; }
        public System.DateTime ContractStartDate { get; set; }
        public System.DateTime ContractEndDate { get; set; }
        public string BloodGroup { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedByEmpNo { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedByEmpNo { get; set; }
        public string LastUpdatedByUser { get; set; }
        public Nullable<int> WorkDurationHours { get; set; }
        public Nullable<int> WorkDurationMins { get; set; }
        public string CompanyContactNo { get; set; }
    }
}
