//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_IDCardHistory
    {
        public int HistoryID { get; set; }
        public int EmpNo { get; set; }
        public bool IsContractor { get; set; }
        public string CardRefNo { get; set; }
        public string Remarks { get; set; }
        public string CardGUID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedByEmpNo { get; set; }
        public string CreatedByEmpName { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<int> LastUpdatedByEmpNo { get; set; }
        public string LastUpdatedByEmpName { get; set; }
        public string LastUpdatedByUser { get; set; }
    }
}
