//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GenPurposeEntities : DbContext
    {
        public GenPurposeEntities()
            : base("name=GenPurposeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PermitCostCenter> PermitCostCenters { get; set; }
        public virtual DbSet<UserDefinedCode> UserDefinedCodes { get; set; }
        public virtual DbSet<UserFormAccess> UserFormAccesses { get; set; }
    }
}
