//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_ShiftTimes
    {
        public int AutoID { get; set; }
        public string ShiftPatCode { get; set; }
        public string ShiftCode { get; set; }
        public Nullable<bool> xxxxxx1 { get; set; }
        public Nullable<System.DateTime> ArrivalFrom { get; set; }
        public Nullable<System.DateTime> ArrivalTo { get; set; }
        public Nullable<System.DateTime> DepartFrom { get; set; }
        public Nullable<System.DateTime> DepartTo { get; set; }
        public Nullable<decimal> TotalHrs { get; set; }
        public Nullable<bool> xxxxxx2 { get; set; }
        public Nullable<System.DateTime> RArrivalFrom { get; set; }
        public Nullable<System.DateTime> RArrivalTo { get; set; }
        public Nullable<System.DateTime> RDepartFrom { get; set; }
        public Nullable<System.DateTime> RDepartTo { get; set; }
        public Nullable<decimal> RTotalHrs { get; set; }
        public Nullable<bool> xxxxxx3 { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> CreatedByEmpNo { get; set; }
        public string CreatedByEmpName { get; set; }
        public string CreatedByUser { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdateEmpNo { get; set; }
        public string LastUpdateEmpName { get; set; }
    
        public virtual Master_ShiftPatternTitles Master_ShiftPatternTitles { get; set; }
    }
}
