//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_DutyType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Master_DutyType()
        {
            this.Tran_DutyRota = new HashSet<Tran_DutyRota>();
        }
    
        public int AutoID { get; set; }
        public string DutyType { get; set; }
        public string Description { get; set; }
        public double DutyAllowance { get; set; }
        public Nullable<decimal> WrkHrsThrday { get; set; }
        public Nullable<decimal> WrkHrsFriday { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tran_DutyRota> Tran_DutyRota { get; set; }
    }
}
