//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OvertimeRequest
    {
        public long OTRequestNo { get; set; }
        public int EmpNo { get; set; }
        public System.DateTime DT { get; set; }
        public int TS_AutoID { get; set; }
        public string CostCenter { get; set; }
        public Nullable<System.DateTime> OTStartTime { get; set; }
        public Nullable<System.DateTime> OTEndTime { get; set; }
        public string OTType { get; set; }
        public string CorrectionCode { get; set; }
        public string MealVoucherEligibility { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string StatusCode { get; set; }
        public string StatusDesc { get; set; }
        public string StatusHandlingCode { get; set; }
        public Nullable<bool> IsClosed { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<bool> IsSubmittedForApproval { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public Nullable<int> CurrentlyAssignedEmpNo { get; set; }
        public string CurrentlyAssignedEmpName { get; set; }
        public string CurrentlyAssignedEmpEmail { get; set; }
        public string ServiceProviderTypeCode { get; set; }
        public string DistListCode { get; set; }
        public Nullable<bool> IsModifiedByHR { get; set; }
        public string OTApproved { get; set; }
        public string OTReason { get; set; }
        public string OTComment { get; set; }
        public Nullable<System.DateTime> OTStartTime_Orig { get; set; }
        public Nullable<System.DateTime> OTEndTime_Orig { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedByEmpNo { get; set; }
        public string CreatedByUserID { get; set; }
        public string CreatedByEmpName { get; set; }
        public string CreatedByEmail { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> LastUpdateEmpNo { get; set; }
        public string LastUpdateUserID { get; set; }
        public string LastUpdateEmpName { get; set; }
        public Nullable<bool> IsOTCommentModified { get; set; }
        public Nullable<bool> IsHold { get; set; }
    }
}
