//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OvertimeWFRoutineHistory
    {
        public int AutoID { get; set; }
        public long OTRequestNo { get; set; }
        public int TS_AutoID { get; set; }
        public System.DateTime RequestSubmissionDate { get; set; }
        public string HistDesc { get; set; }
        public int HistCreatedBy { get; set; }
        public string HistCreatedName { get; set; }
        public Nullable<System.DateTime> HistCreatedDate { get; set; }
    }
}
