//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermitCostCenter
    {
        public int PermitID { get; set; }
        public int PermitEmpNo { get; set; }
        public string PermitCostCenter1 { get; set; }
        public int PermitAppID { get; set; }
        public Nullable<int> PermitCreatedBy { get; set; }
        public Nullable<System.DateTime> PermitCreatedDate { get; set; }
        public Nullable<int> PermitModifiedBy { get; set; }
        public Nullable<System.DateTime> PermitModifiedDate { get; set; }
    
        public virtual UserDefinedCode UserDefinedCode { get; set; }
    }
}
