//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_GetUserFormAccessInfo_Result2
    {
        public string ApplicationName { get; set; }
        public Nullable<int> EmpNo { get; set; }
        public string EmpName { get; set; }
        public string Position { get; set; }
        public string CostCenter { get; set; }
        public string FormCode { get; set; }
        public string FormName { get; set; }
        public string UserFrmCRUDP { get; set; }
        public bool FormPublic { get; set; }
        public Nullable<int> CreatedByEmpNo { get; set; }
        public string CreatedByEmpName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LastUpdatedByEmpNo { get; set; }
        public string LastUpdatedByEmpName { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    }
}
