//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_GetDailyAttendanceReport_Result2
    {
        public string BusinessUnit { get; set; }
        public string BusinessUnitName { get; set; }
        public int EmpNo { get; set; }
        public string EmpName { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public Nullable<System.DateTime> dtIN { get; set; }
        public Nullable<System.DateTime> dtOUT { get; set; }
        public Nullable<int> NetMinutes { get; set; }
        public string ShiftPatCode { get; set; }
        public string ShiftCode { get; set; }
        public string Actual_ShiftCode { get; set; }
        public Nullable<System.DateTime> OTStartTime { get; set; }
        public Nullable<System.DateTime> OTEndTime { get; set; }
        public string OTType { get; set; }
        public Nullable<int> NoPayHours { get; set; }
        public Nullable<bool> ShiftAllowance { get; set; }
        public string ShiftAllowanceDesc { get; set; }
        public Nullable<int> Duration_ShiftAllowance_Evening { get; set; }
        public Nullable<int> Duration_ShiftAllowance_Night { get; set; }
        public Nullable<bool> IsSalStaff { get; set; }
        public string Remark { get; set; }
        public string ShiftTiming { get; set; }
    }
}
