//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_GetCostCenter_Result1
    {
        public string BusinessUnit { get; set; }
        public string BusinessUnitName { get; set; }
        public string ParentBU { get; set; }
        public Nullable<double> Superintendent { get; set; }
        public Nullable<double> CostCenterManager { get; set; }
    }
}
