//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_GetEmployeeDirectory_Result3
    {
        public Nullable<int> EmpNo { get; set; }
        public string EmpName { get; set; }
        public string Position { get; set; }
        public Nullable<int> SupervisorNo { get; set; }
        public string SupervisorName { get; set; }
        public string BusinessUnit { get; set; }
        public string BusinessUnitName { get; set; }
        public string Religion { get; set; }
        public string JobCategory { get; set; }
        public string Sex { get; set; }
        public Nullable<int> GradeCode { get; set; }
        public string PayStatus { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public Nullable<double> YearsOfService { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<double> Age { get; set; }
        public string TelephoneExt { get; set; }
        public string MobileNo { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string EmpEmail { get; set; }
    }
}
