//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_GetTimesheetUDCCodes_Result2
    {
        public string UDCCode { get; set; }
        public string UDCDesc1 { get; set; }
        public string UDCDesc2 { get; set; }
    }
}
