//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_GetLeaveInformation_Result1
    {
        public Nullable<System.DateTime> LeaveOpeningDate { get; set; }
        public Nullable<System.DateTime> LeaveEndingDate { get; set; }
        public Nullable<System.DateTime> LeaveEmpServiceDate { get; set; }
        public Nullable<double> LeaveEntitlement { get; set; }
        public Nullable<double> LeaveTakenAsOfDate { get; set; }
        public Nullable<double> LeaveTakenCurrentYear { get; set; }
        public Nullable<double> LeaveCurrentBal { get; set; }
    }
}
