//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_Get_Permitted_CostCenter_V2_Result1
    {
        public Nullable<int> PermitEmpNo { get; set; }
        public string PermitCostCenter { get; set; }
    }
}
