//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_GetPunctualityReport_Result1
    {
        public string AttendanceDate { get; set; }
        public Nullable<double> Total_0700_Below { get; set; }
        public Nullable<double> Total_0710_0720 { get; set; }
        public Nullable<double> Total_0720_0730 { get; set; }
        public Nullable<double> Total_0730_0740 { get; set; }
        public Nullable<double> Total_0740_0750 { get; set; }
        public Nullable<double> Total_0750_0800 { get; set; }
        public Nullable<double> Total_0800_Above { get; set; }
        public Nullable<double> Total_Absent { get; set; }
    }
}
