//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_GetEmpAttendanceHistory_Result3
    {
        public int AutoID { get; set; }
        public int EmpNo { get; set; }
        public string EmpName { get; set; }
        public string Position { get; set; }
        public string BusinessUnit { get; set; }
        public string BusinessUnitName { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public Nullable<System.DateTime> dtIn { get; set; }
        public Nullable<System.DateTime> dtOut { get; set; }
        public string ShiftPatCode { get; set; }
        public string ShiftCode { get; set; }
        public string Actual_ShiftCode { get; set; }
        public Nullable<int> WorkDurationMinutes { get; set; }
        public string WorkDurationHours { get; set; }
        public Nullable<int> OTDurationMinutes { get; set; }
        public string OTDurationHours { get; set; }
        public Nullable<int> NoPayHours { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Duration_Required { get; set; }
        public int DayOffDuration { get; set; }
    }
}
