//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_GetEmployeeInfo_JDE_Result2
    {
        public Nullable<int> EmpNo { get; set; }
        public string EmpName { get; set; }
        public string ReligionCode { get; set; }
        public string JobCategoryCode { get; set; }
        public string SexCode { get; set; }
        public string CostCenter { get; set; }
        public string CostCenterName { get; set; }
        public string Company { get; set; }
        public Nullable<int> GradeCode { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public Nullable<System.DateTime> DateResigned { get; set; }
        public string PayStatus { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ActualCostCenter { get; set; }
        public Nullable<double> YearsOfService { get; set; }
    }
}
