//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    
    public partial class Pr_PunctualitySummaryReport_Result1
    {
        public int EmpNo { get; set; }
        public string EmpName { get; set; }
        public string ShiftPatCode { get; set; }
        public string ShiftCode { get; set; }
        public string Actual_ShiftCode { get; set; }
        public string CostCenter { get; set; }
        public string CostCenterName { get; set; }
        public Nullable<System.DateTime> DT { get; set; }
        public Nullable<System.DateTime> dtIN { get; set; }
        public Nullable<System.DateTime> dtOUT { get; set; }
        public Nullable<System.DateTime> MaxArrivalTime { get; set; }
        public int ArrivalTimeDiff { get; set; }
        public string Remarks { get; set; }
        public string LeaveType { get; set; }
    }
}
