//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Values
    {
        public int AutoID { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0200 { get; set; }
        public string CODE_UDC_AbsenceReasonCode { get; set; }
        public string CODE_UDC_ChangeType { get; set; }
        public string CODE_UDC_DayOfWeek { get; set; }
        public string CODE_UDC_GroupCode { get; set; }
        public string CODE_UDC_LeaveType { get; set; }
        public string CODE_UDC_ReligionCode { get; set; }
        public string CODE_UDC_ShiftCode { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0300 { get; set; }
        public string CODE_Shift_Morning { get; set; }
        public string CODE_Shift_Evening { get; set; }
        public string CODE_Shift_Night { get; set; }
        public string CODE_Shift_Off { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0305 { get; set; }
        public string CODE_SpecialShift_Pat { get; set; }
        public string CODE_TimeResolution { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0310 { get; set; }
        public string CODE_Remark_Absent { get; set; }
        public string CODE_SystemSuppliedIN { get; set; }
        public string CODE_SystemSuppliedOUT { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0350 { get; set; }
        public Nullable<System.DateTime> DT_SwipeLastProcessed { get; set; }
        public Nullable<System.DateTime> DT_SwipeNewProcess { get; set; }
        public Nullable<System.DateTime> DT_ManualTimeSheetLastEntered { get; set; }
        public Nullable<System.DateTime> DT_ShiftPatternLastUpdated { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0400 { get; set; }
        public string Code_EnabledUserLogin { get; set; }
        public string Code_ApplicationSecurityType { get; set; }
        public string Code_BusinessUnitSecurityType { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0450 { get; set; }
        public string Code_AdminUserID1 { get; set; }
        public string Code_AdminUserID2 { get; set; }
        public string Code_AdminUserID3 { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0500 { get; set; }
        public string Code_DefaultShiftPat { get; set; }
        public string Code_DefaultShiftCode { get; set; }
        public string Code_FirstShiftOfDay { get; set; }
        public string Code_ChangeTypeDeffered { get; set; }
        public string Code_ChangeTypeTemporary { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0600 { get; set; }
        public string Code_MuslimReligion { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0700 { get; set; }
        public string Code_JobCategory_SalaryStaff { get; set; }
        public string Code_JobCategory_NonSalaryStaff { get; set; }
        public string Code_JobCategory_Driver { get; set; }
        public string Code_JobCategory_Hedger { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0800 { get; set; }
        public string Code_ReaderManualLocation { get; set; }
        public Nullable<int> Code_ReaderManualOut { get; set; }
        public Nullable<int> Code_ReaderManuaIn { get; set; }
        public string Code_ReaderAccessGranted { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0850 { get; set; }
        public string Code_SwipeSource_Manual { get; set; }
        public string Code_SwipeSource_Automatic { get; set; }
        public string Code_SwipeSource_Absent { get; set; }
        public string Code_SwipeSource_ShiftSpan { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX0900 { get; set; }
        public string Code_ROA_BusinessTrip { get; set; }
        public string Code_ROA_MaternityBenifit { get; set; }
        public string Code_ROA_TrainingLocal { get; set; }
        public string Code_ROA_TrainingForeign { get; set; }
        public string Code_ROA_DIL_Used_Dept { get; set; }
        public string Code_ROA_DIL_Used_HR { get; set; }
        public Nullable<bool> XXXXXX0950 { get; set; }
        public string Code_DayInLieu_Entitiled_System { get; set; }
        public string Code_DayInLieu_Entitiled_HR { get; set; }
        public string Code_DayInLieu_USED_Admin { get; set; }
        public string Code_DayInLieu_USED_Dept { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1000 { get; set; }
        public string Code_PublicHolidy { get; set; }
        public string Code_Ramadan { get; set; }
        public string Code_DIL_DayWorker { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1100 { get; set; }
        public string Code_ContGroup_Sal { get; set; }
        public string Code_ContGroup_NonSal { get; set; }
        public string Code_ContGroup_Seasonal { get; set; }
        public string Code_ContGroup_Visitor { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1200 { get; set; }
        public Nullable<int> Minutes_GracePeriod { get; set; }
        public Nullable<int> Minutes_MinOT_NSS { get; set; }
        public Nullable<int> Minutes_MinOT_SS { get; set; }
        public Nullable<int> Minutes_MinShiftAllowance { get; set; }
        public Nullable<int> Minutes_MaternityAbsence { get; set; }
        public Nullable<int> Minutes_MinDILentitlement { get; set; }
        public Nullable<int> Minutes_AbsenceCutOff { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1220 { get; set; }
        public Nullable<int> Hours_MaxWorking { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1230 { get; set; }
        public Nullable<int> Days_minEditTimeSheet { get; set; }
        public Nullable<int> Days_MaxBusTrip { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1240 { get; set; }
        public Nullable<int> Months_DILexpiry { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1400 { get; set; }
        public string Project_URL_prefix { get; set; }
        public string Report_URL_prefix { get; set; }
        public string SPU_URL_Prefix { get; set; }
        public string Download_URL_prefix { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1500 { get; set; }
        public string Code_OTtype_Regular { get; set; }
        public string Code_OTtype_PublicHoliday { get; set; }
        public string Code_OTtype_DILdw { get; set; }
        public string Code_OTtype_DayOff { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1600 { get; set; }
        public string CODE_AbsenceColumn_ROA { get; set; }
        public string CODE_AbsenceColumn_Leave { get; set; }
        public string CODE_AbsenceColumn_Cal_Holiday { get; set; }
        public string CODE_AbsenceColumn_Cal_DILdw { get; set; }
        public string CODE_AbsenceColumn_DayOff { get; set; }
        public string CODE_AbsenceColumn_ShiftSpan { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1700 { get; set; }
        public string EMAILs_Alert_System { get; set; }
        public string EMAILs_Alert_HR { get; set; }
        public string SMTPServerName { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1800 { get; set; }
        public Nullable<bool> DummyColumn { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string MarqueeText { get; set; }
        public Nullable<bool> BackupDBbeforeProcessingTS { get; set; }
        public string SystemDownMsg { get; set; }
        public Nullable<bool> SystemDownFlg { get; set; }
        public string TrainingSec1 { get; set; }
        public string TrainingSec2 { get; set; }
        public string TrainingSec3 { get; set; }
        public string CODE_Shift_Day { get; set; }
        public string IsMedicalNurse1 { get; set; }
        public string IsMedicalNurse2 { get; set; }
        public string IsMedicalNurse3 { get; set; }
        public string IsMedicalNurse4 { get; set; }
        public string IsMedicalNurse5 { get; set; }
        public string IsMedicalNurse6 { get; set; }
        public string DW_EndOfDay_From { get; set; }
        public string DW_EndOfDay_To { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX1900 { get; set; }
        public string HRuser1 { get; set; }
        public string HRuser2 { get; set; }
        public string HRuser3 { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX2000 { get; set; }
        public Nullable<int> Minutes_Min_ShiftSpanOT_Full { get; set; }
        public Nullable<int> Minutes_Min_ShiftSpanOT_Day1 { get; set; }
        public Nullable<int> Minutes_Min_ShiftSpanOT_Day2 { get; set; }
        public Nullable<bool> XXXXXXXXXXXXXXX2100 { get; set; }
        public Nullable<int> Upload_ID { get; set; }
        public Nullable<System.DateTime> DIL_switch_date { get; set; }
        public string WeekEndDay1 { get; set; }
        public string WeekEndDay2 { get; set; }
        public Nullable<int> CommandTimeout { get; set; }
        public Nullable<int> Minutes_MinOT_SS_Ramadan { get; set; }
        public Nullable<System.DateTime> Hide_OT_From { get; set; }
        public Nullable<System.DateTime> Hide_OT_To { get; set; }
        public Nullable<bool> AllowTimesheetProcessing { get; set; }
        public string LIST_of_Timesheet_Users { get; set; }
        public string LIST_of_Timesheet_developers { get; set; }
        public bool CheckSwipeValidation { get; set; }
        public Nullable<int> MealVoucherEligibleMins { get; set; }
    }
}
