//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran_ShiftPatternChanges
    {
        public int AutoID { get; set; }
        public int EmpNo { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public string ShiftPatCode { get; set; }
        public decimal ShiftPointer { get; set; }
        public string ChangeType { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
    }
}
