//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran_Timesheet_Extra
    {
        public int XID_AutoID { get; set; }
        public Nullable<System.DateTime> OTstartTime { get; set; }
        public Nullable<System.DateTime> OTendTime { get; set; }
        public string OTtype { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string Comment { get; set; }
        public string OTApproved { get; set; }
        public string OTReason { get; set; }
    }
}
