//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitorPassLog
    {
        public long LogID { get; set; }
        public string VisitorName { get; set; }
        public int VisitorCardNo { get; set; }
        public string IDNumber { get; set; }
        public int VisitEmpNo { get; set; }
        public System.DateTime VisitDate { get; set; }
        public Nullable<System.DateTime> VisitTimeIn { get; set; }
        public Nullable<System.DateTime> VisitTimeOut { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedByEmpNo { get; set; }
        public string CreatedByUserID { get; set; }
        public string CreatedByEmpName { get; set; }
        public string CreatedByEmpEmail { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> LastUpdateEmpNo { get; set; }
        public string LastUpdateUserID { get; set; }
        public string LastUpdateEmpName { get; set; }
        public string LastUpdateEmpEmail { get; set; }
    }
}
