//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GARMCO.AMS.TAS.DAL.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_MainGateSwipeRawData
    {
        public Nullable<int> EmpNo { get; set; }
        public Nullable<System.DateTime> SwipeDate { get; set; }
        public Nullable<System.DateTime> SwipeTime { get; set; }
        public string SwipeLocation { get; set; }
        public string SwipeType { get; set; }
        public int LocationCode { get; set; }
        public int ReaderNo { get; set; }
        public string SwipeCode { get; set; }
        public string LocationName { get; set; }
        public string ReaderName { get; set; }
        public string LName { get; set; }
    }
}
